version: "3.8"

services:
  app:
    container_name: holidaymanager-frontend
    build:
      context: .
      args:
        API_HOST_URL: ${API_HOST_URL}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_HOST_URL=${API_HOST_URL}
    restart: unless-stopped
